///////////////////////////////////////////////////////////
//  IShapeContainer.as
//  Macromedia ActionScript Implementation of the Interface IShapeContainer
//  Generated by Enterprise Architect
//  Created on:      01-Apr-2008 8:09:25 AM
//  Original author: alessandro crugnola
///////////////////////////////////////////////////////////

package com.aviary.display
{
	import com.aviary.geom.IShape;

	/**
	 * @author alessandro crugnola
	 * @version 1.0
	 * @created 01-Apr-2008 8:09:25 AM
	 */
	public interface IShapeContainer extends IShapeDisplay
	{
		function get shape(): IShape;
		function set shape( value: IShape ): void;
		function get uid( ): String;
		
	}//end IShapeContainer

}