///////////////////////////////////////////////////////////
//  FillType.as
//  Macromedia ActionScript Implementation of the Class FillType
//  Generated by Enterprise Architect
//  Created on:      01-Apr-2008 8:09:22 AM
//  Original author: alessandro crugnola
///////////////////////////////////////////////////////////

/**
 * @author alessandro crugnola
 * @version 1.0
 * @created 01-Apr-2008 8:09:22 AM
 */
 
package com.aviary.graphics
{
	public class FillType
	{
	    static public const NONE: uint = 1;
	    static public const SOLID: uint = 2;
	    static public const LINEAR: uint = 4;
	    static public const RADIAL: uint = 8;
	
	    public function FillType()
	    {
	    }
	
	}//end FillType
}