///////////////////////////////////////////////////////////
//  IVectorFill.as
//  Macromedia ActionScript Implementation of the Interface IVectorFill
//  Generated by Enterprise Architect
//  Created on:      01-Apr-2008 8:09:25 AM
//  Original author: alessandro crugnola
///////////////////////////////////////////////////////////

package com.aviary.graphics
{
	
	import com.aviary.raven.utils.ICloneable;
	
	import flash.display.Graphics;
	import flash.events.IEventDispatcher;
	import flash.geom.Rectangle;
	
	/**
	 * @author alessandro crugnola
	 * @version 1.0
	 * @created 01-Apr-2008 8:09:25 AM
	 */
	public interface IVectorFill extends IEventDispatcher, ICloneable, IGradient
	{
		/**
		 * 
		 * @param target
		 * @param rc
		 * @param type
		 * @param angle
		 * @param spread
		 * @param interpolation
		 * @param focalpoint    focalpoint
		 */
		function begin(target:Graphics, rc:Rectangle, type:uint = 1, angle:Number = 0, spread:String = 'pad', interpolation:String = 'rgb', focalpoint:Number = 0): void;
	
		/**
		 * 
		 * @param target    target
		 */
		function end(target:Graphics): void;
		
		function toString(): String;
	}//end IVectorFill
}