///////////////////////////////////////////////////////////
//  StrokeType.as
//  Macromedia ActionScript Implementation of the Class StrokeType
//  Generated by Enterprise Architect
//  Created on:      01-Apr-2008 8:09:31 AM
//  Original author: alessandro crugnola
///////////////////////////////////////////////////////////

package com.aviary.graphics
{
	/**
	 * @author alessandro crugnola
	 * @version 1.0
	 * @created 01-Apr-2008 8:09:31 AM
	 */
	public class StrokeType
	{
	    static public const NONE: uint = 1;
	    static public const SOLID: uint = 2;
	    static public const LINEAR: uint = 4;
	    static public const RADIAL: uint = 8;
	
	    public function StrokeType()
	    {
	    }
	
	}//end StrokeType
}