///////////////////////////////////////////////////////////
//  HandleType.as
//  Macromedia ActionScript Implementation of the Class HandleType
//  Generated by Enterprise Architect
//  Created on:      01-Apr-2008 8:09:23 AM
//  Original author: alessandro crugnola
///////////////////////////////////////////////////////////

package com.aviary.geom.controls
{
	/**
	 * @author alessandro crugnola
	 * @version 1.0
	 * @created 01-Apr-2008 8:09:23 AM
	 */
	public class HandleType
	{
	    static public const CONTROL_POINT: uint = 1 << 0;	// point anchor
	    static public const CONTROL_FORM: uint = 1 << 1;	// bezier
	    static public const FILL_START_POINT: uint = 1 << 2;
	    static public const FILL_END_POINT: uint = 1 << 3;
	    static public const FILL_STOP_POINT: uint = 1 << 4;

	    public function HandleType()
	    {
	    }

	}//end HandleType

}