///////////////////////////////////////////////////////////
//  SegmentHandle.as
//  Macromedia ActionScript Implementation of the Class SegmentHandle
//  Generated by Enterprise Architect
//  Created on:      01-Apr-2008 8:09:29 AM
//  Original author: alessandro crugnola
///////////////////////////////////////////////////////////

package com.aviary.geom.controls
{
	import com.aviary.geom.path.ISegment;

	/**
	 * Specific handle for segments
	 * @author alessandro crugnola
	 * @version 1.0
	 * @created 01-Apr-2008 8:09:29 AM
	 */
	public class SegmentHandle extends Handle
	{
	    protected var m_segment: ISegment;
	    protected var m_children: Array;
	    protected var m_parentHandle: IHandle;

	    /**
	     * 
	     * @param handle_name
	     * @param x
	     * @param y
	     * @param seg
	     * @param type    type
	     */
	    public function SegmentHandle( handle_name: String, x: Number, y: Number, seg: ISegment, type: uint = 1 )
	    {
			super( handle_name, x, y, type );
			m_segment  = seg;
			m_children = new Array( );	    	
	    }

	    public function get parentHandle(): IHandle
	    {
	    	return m_parentHandle;
	    }

	    /**
	     * 
	     * @param value    value
	     */
	    public function set parentHandle( value: IHandle ): void
	    {
			if( value is SegmentHandle )
			{
				var svalue: SegmentHandle = value as SegmentHandle;
				if( svalue.children.indexOf( this ) == -1 )
				{
					if( svalue.children.push( this ) );
				}
			}
			if( value == null && m_parentHandle != null )
			{
				( m_parentHandle as SegmentHandle ).children.splice( ( m_parentHandle as SegmentHandle ).children.indexOf( this ), 1 ); 
			}
			m_parentHandle = value;
	    }

	    public function get children(): Array
	    {
			return m_children;
	    }

	    /**
	     * Get the controlled segment
	     */
	    public function get segment(): ISegment
	    {
	    	return m_segment;
	    }

	}//end SegmentHandle

}