///////////////////////////////////////////////////////////
//  ShapeEvent.as
//  Macromedia ActionScript Implementation of the Class ShapeEvent
//  Generated by Enterprise Architect
//  Created on:      01-Apr-2008 8:09:29 AM
//  Original author: alessandro crugnola
///////////////////////////////////////////////////////////

package com.aviary.events
{
	import flash.events.Event;
	
	/**
	 * @author alessandro crugnola
	 * @version 1.0
	 * @created 01-Apr-2008 8:09:30 AM
	 */
	public class ShapeEvent extends Event
	{
	    static public const SHAPE_UPDATE: String = 'shapeUpdate';

	    /**
	     * 
	     * @param type
	     * @param bubbles
	     * @param cancelable    cancelable
	     */
	    public function ShapeEvent(type:String, bubbles:Boolean = false, cancelable:Boolean = false)
	    {
	    	super( type, bubbles, cancelable );
	    }

	}//end ShapeEvent

}