///////////////////////////////////////////////////////////
//  HandleEvent.as
//  Macromedia ActionScript Implementation of the Class HandleEvent
//  Generated by Enterprise Architect
//  Created on:      01-Apr-2008 8:09:23 AM
//  Original author: alessandro crugnola
///////////////////////////////////////////////////////////

package com.aviary.events
{
	import flash.geom.Point;
	import flash.events.Event;
	
	/**
	 * @author alessandro crugnola
	 * @version 1.0
	 * @created 01-Apr-2008 8:09:23 AM
	 */
	public class HandleEvent extends Event
	{
	    static public const HANDLE_CHANGE: String = 'handleChange';
	    static public const HANDLE_UPDATE: String = 'handleUpdate';
	    public var old_point: Point;

	    /**
	     * 
	     * @param type
	     * @param pt    pt
	     */
	    public function HandleEvent( type: String, pt: Point = null )
	    {
	    	super( type, false, false );
	    	old_point = pt;
	    }

	}//end HandleEvent

}