///////////////////////////////////////////////////////////
//  SegmentEvent.as
//  Macromedia ActionScript Implementation of the Class SegmentEvent
//  Generated by Enterprise Architect
//  Created on:      01-Apr-2008 8:09:29 AM
//  Original author: alessandro crugnola
///////////////////////////////////////////////////////////

package com.aviary.events
{
	import flash.events.Event;
	
	/**
	 * @author alessandro crugnola
	 * @version 1.0
	 * @created 01-Apr-2008 8:09:29 AM
	 */
	public class SegmentEvent extends Event
	{
	    static public const SEGMENT_CHANGE: String = 'segmentChange';

	    /**
	     * 
	     * @param type
	     * @param bubbles
	     * @param cancelable    cancelable
	     */
	    public function SegmentEvent(type:String, bubbles:Boolean = false, cancelable:Boolean = false)
	    {
	    	super( type, bubbles, cancelable );
	    }

	}//end SegmentEvent

}