///////////////////////////////////////////////////////////
//  IShapeDisplay.as
//  Macromedia ActionScript Implementation of the Interface IShapeDisplay
//  Generated by Enterprise Architect
//  Created on:      01-Apr-2008 8:09:25 AM
//  Original author: alessandro crugnola
///////////////////////////////////////////////////////////

package com.aviary.display
{
	import com.aviary.graphics.IVectorFill;
	import com.aviary.graphics.IVectorStroke;
	
	/**
	 * @author alessandro crugnola
	 * @version 1.0
	 * @created 01-Apr-2008 8:09:25 AM
	 */
	public interface IShapeDisplay
	{
		function get stroke(): IVectorStroke;

		/**
		 * 
		 * @param value    value
		 */
		function set stroke(value:IVectorStroke): void;

		function get fill(): IVectorFill;

		/**
		 * 
		 * @param value    value
		 */
		function set fill(value:IVectorFill): void;

		/**
		 * 
		 * @param value    value
		 */
		function set fillAngle(value:Number): void;

		function get fillAngle(): Number;

		/**
		 * 
		 * @param value    value
		 */
		function set fillRotation(value:Number): void;

		function get fillRotation(): Number;

		/**
		 * 
		 * @param t    t
		 */
		function set fillType(t:uint): void;

		function get fillType(): uint;

		/**
		 * 
		 * @param t    t
		 */
		function set strokeType(t:uint): void;

		function get strokeType(): uint;

		function get focalPointRatio(): Number;

		/**
		 * 
		 * @param value    value
		 */
		function set focalPointRatio(value:Number): void;

		/**
		 * 
		 * @param value    value
		 */
		function set spreadMethod(value:String): void;

		function get spreadMethod(): String;

		/**
		 * 
		 * @param value    value
		 */
		function set interpolationMethod(value:String): void;

		function get interpolationMethod(): String;
	}//end IShapeDisplay

}