///////////////////////////////////////////////////////////
//  Graphics2D.as
//  Macromedia ActionScript Implementation of the Class Graphics2D
//  Generated by Enterprise Architect
//  Created on:      01-Apr-2008 8:09:23 AM
//  Original author: alessandro crugnola
///////////////////////////////////////////////////////////

package com.aviary.graphics
{
	import com.aviary.geom.IShape;
	
	import flash.display.Graphics;
	
	/**
	 * GeometrySDK Given a flash.display.Graphics it will render a custom IShape
	 * @author alessandro crugnola
	 * @version 1.0
	 * @created 01-Apr-2008 8:09:23 AM
	 */
	public class AbstractGraphics2D implements IGraphics2D
	{
	    protected var m_stroke: IVectorStroke;
	    protected var m_fill: IVectorFill;
	    protected var m_graphic: Graphics;
	    protected var m_strokeType: uint = 0;
	    protected var m_fillType: uint = 0;
	
	    /**
	     * 
	     * @param gr
	     * @param stroke
	     * @param fill    fill
	     */
	    public function AbstractGraphics2D( gr: Graphics, stroke: IVectorStroke, fill: IVectorFill )
	    {
	    	m_graphic = gr;
	    	m_stroke  = stroke;
	    	m_fill    = fill;
	    }
	
	    /**
	     * Force the type of the stroke to be drawn
	     */
	    public function get strokeType(): uint
	    {
	    	return m_strokeType as uint;
	    }

	    /**
	     * 
	     * @param value    value
	     */
	    public function set strokeType( value: uint ): void
	    {
	    	m_strokeType = value;
	    }
	    
	    public function set fillType( value: uint ): void
	    {
	    	m_fillType = value;
	    }
	    
	    public function get fillType( ): uint
	    {
	    	return m_fillType;
	    }
	
	    public function get stroke(): IVectorStroke
	    {
	    	return m_stroke;
	    }
	
	    public function get fill(): IVectorFill
	    {
	    	return m_fill;
	    }
	
	    public function get graphics(): Graphics
	    {
	    	return m_graphic;
	    }
	    
		public function clear( ): void
		{
			m_graphic.clear( );
		}	    
	
	    /**
	     * Render the current shape
	     * @see IShape
	     * 
	     * @param value    value
	     */
	    public function render( value: IShape ): void
	    {
	    	throw new Error("NonImplementationException");
	    }
	
	}//end Graphics2D
}