///////////////////////////////////////////////////////////
//  IGradient.as
//  Macromedia ActionScript Implementation of the Interface IGradient
//  Generated by Enterprise Architect
//  Created on:      01-Apr-2008 8:09:24 AM
//  Original author: alessandro crugnola
///////////////////////////////////////////////////////////

/**
 * @author alessandro crugnola
 * @version 1.0
 * @created 01-Apr-2008 8:09:24 AM
 */
package com.aviary.graphics
{
	import mx.graphics.GradientEntry;
	
	public interface IGradient
	{
		function get gstops(): Object;
	
		function get entries(): Array;
	
		/**
		 * 
		 * @param value    value
		 */
		function set entries(value:Array): void;
	
		/**
		 * 
		 * @param value
		 * @param pos    pos
		 */
		function setEntryAt(value:GradientEntry, pos:uint): void;
	
		/**
		 * 
		 * @param pos    pos
		 */
		function getEntryAt(pos:uint): GradientEntry;
	}//end IGradient
}